Repository redis/hiredis, pull requests merged in 2022-08, with the labels that each got.

#1087 Maintain backward compatibiliy withour onConnect callback.
  README.md
  async.c
  async.h
  test.c
Labels: async, bug

#1091 Fix some undefined behavior
  examples/example-libevent-ssl.c
  examples/example-ssl.c
Labels: bug

#964 Fix potential fault at createDoubleObject
  hiredis.c
Labels: bug

#959 Add do while(0) protection for macros
  hiredis.h
Labels: maintenance
