Repository redis/hiredis, pull requests merged in 2023-07, with the labels that each got.

#1205 Remove support in deprecated TLS versions 1.0 and 1.1
  ssl.c
Labels: maintenance, breakingchange

#1202 Version 1.2.0
  CHANGELOG.md
  hiredis.h
Labels: maintenance

#1208 Bump development SONAME.
  hiredis.h
Labels: maintenance

#1210 Allow disabling the -Werror flag.
  Makefile
Labels: maintenance

#1209 Fix a false positive warning of gcc 12+ -Werror=maybe-uninitialized
  test.c
Labels: maintenance

#1213 Retry poll(2) if we are intterupted.
  net.c
Labels: bug

#1214 Document poll(2) logic changes.
  README.md
Labels: maintenance

#1212 Add a panic helper for non-assert aborts.
  test.c
Labels: maintenance
