Repository redis/hiredis, pull requests merged in 2025-05, with the labels that each got.

#1298 Define ssize_t as intptr_t in Windows
  hiredis.h
  sds.h
  sockcompat.h
Labels: maintenance, portability

#1300 Fix CI on MacOS runners.
  .github/workflows/build.yml
Labels: maintenance

#1299 Fix buffer overflow in tests.
  test.c
Labels: bug
